(library
 (name tui_test)
 (libraries
  jsip_tui
  jsip_types
  jsip_replay
  jsip_parsing
  bonsai_term
  notty-community
  expect_test_helpers_core
  core)
 ; see lib/parsing/test/dune: work around this switch's ppx_expect
 ; mis-resolving dune's -source-tree-root
 (inline_tests
  (deps
   (glob_files_rec ../../../testing/*))
  (flags
   (:standard -source-tree-root .)))
 (preprocess
  (pps ppx_jane)))
